/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kravanhFirebaseMessage;

import org.junit.Test;

public class kravanhFirebaseMessageTest {
    @Test
    public void testSomeLibraryMethod() {
        boolean s = false;
        int userId = 1;
        kravanhFirebaseMessage kvMessage = new kravanhFirebaseMessage().setProjectId("56280728680").setAuthKey(
                "AAAADRqXxGg:APA91bG8vBPS7JkyGm-vpivGLNp5XHaYBiZlrlPb0pOubEqOHfdHjgM6ztdCsrG0IkpPVH5BuzaHTWzRbaAOwIhWAOat0SWZvV0Damt_jmzgr_guo8lT3g-ZsJpl36KlABQfThX-9Vc5");
        s = kvMessage.registerDevice(
                "fUE_h_ZVP_cZZs0sUyQfRc:APA91bGkC9sXXIyCEG6FRbz67OlF79qte9Ug4Yq4KPXpq8cqB4B0Rx8G_Jfl9dPxsEcBIpIsbXdWqPh-HqQslvfGmXgXumrFuBk3NZ7aKY9rNuv2owwYdFLTJp0XObyh8ZzWGa2vTIu_",
                userId);
        System.out.println(s);
        s = kvMessage.sendNotification("Hi", "Tos Hob Bay", 1);
        System.out.println(s);
    }
}
